class AppEnum {
  static final String ON_VERIFICATION_CONFIRM_ORDER =
      "ON_VERIFICATION_CONFIRM_ORDER";
  static final String ON_VERIFICATION_CONFIRM_REQUEST_ORDER =
      "ON_VERIFICATION_CONFIRM_REQUEST_ORDER";
  static final String ON_VERIFICATION_CONFIRM_CONSULT_PHARMACIST_ORDER =
      "ON_VERIFICATION_CONFIRM_CONSULT_PHARMACIST_ORDER";
  static final String ON_VERIFICATION_FROM_USER_DETAILS_PAGE =
      "ON_VERIFICATION_CONFIRM_CONSULT_PHARMACIST_ORDER";
  static final String LOGIN_USING_REFERRAL_CODE =
      "LOGIN_USING_REFERRAL_CODE";
}
