class AppEnum {
  static const String ON_VERIFICATION_CONFIRM_ORDER =
      "ON_VERIFICATION_CONFIRM_ORDER";
  static const String ON_VERIFICATION_CONFIRM_REQUEST_ORDER =
      "ON_VERIFICATION_CONFIRM_REQUEST_ORDER";
  static const String ON_VERIFICATION_CONFIRM_CONSULT_PHARMACIST_ORDER =
      "ON_VERIFICATION_CONFIRM_CONSULT_PHARMACIST_ORDER";
  static const String ON_VERIFICATION_FROM_USER_DETAILS_PAGE =
      "ON_VERIFICATION_CONFIRM_CONSULT_PHARMACIST_ORDER";
  static const String LOGIN_USING_REFERRAL_CODE =
      "LOGIN_USING_REFERRAL_CODE";
  static const String HOME_PAGE =
      "HOME PAGE";
  static const String CONFIRM_INVOICE_PAGE =
      "CONFIRM INVOICE PAGE";
}
